### ISSUE TITLE
Security test error

### ISSUE THREAD

**Issue by jongeuni** [Melan-Etumos/me-backend#19]
```
Parameter 0 of constructor in com.dsm.me.global.security.SecurityAuthenticationFilter required a bean of type 'com.dsm.me.global.security.token.JwtUtil' that could not be found.

Action:

Consider defining a bean of type 'com.dsm.me.global.security.token.JwtUtil' in your configuration.

2022-03-15 23:48:56.532 ERROR 28504 --- [    Test worker] o.s.test.context.TestContextManager      : Caught exception while allowing TestExecutionListener [org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@7a0e1b5e] to prepare test instance [com.dsm.me.model.user.controller.EmailControllerTests@24197b13]

java.lang.IllegalStateException: Failed to load ApplicationContext
```
Bean 생성이 안 되는 문제 발생. WebMvcTest는 `@Component`, `@Service`, `@Repository`을 [스캔하지 않기 때문임.](https://csy7792.tistory.com/334)

**Comment by jongeuni** [comment]
해결 후 다른 오류 발생.

<br>

```
Attribute name must not be null
java.lang.IllegalArgumentException: Attribute name must not be null
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at org.springframework.mock.web.MockHttpServletRequest.setAttribute(MockHttpServletRequest.java:762)
	at javax.servlet.ServletRequestWrapper.setAttribute(ServletRequestWrapper.java:259)

```

`@AutoConfigureMockMvc`를 사용해 [filter을 false](https://stackoverflow.com/questions/62794979/spring-boot-webmvctest-what-is-causing-illegalargumentexception-here) 해주고 해결.
